### ISSUE TITLE
スマホ対応

### ISSUE THREAD

**Issue by Nagarei** [KaijoComputer/KaijoComputer.github.io#14]
@platypus999
スマホ対応にするために画面の幅からレイアウトを変えるようにしたいのですが、その場合はプルダウンメニューにしていいですか？

---

@Nagarei
それが良いと思います。その際twitterとfacebookは一番下に移動かな

---

@platypus999
そうします
適当にjsを作っておきます

**Comment by platypus999** [comment]
スマホ対応のサイトを作るにあたり、
htmlのheadにcssを直書きする様子が散見されました。（僕もそうしていました）
しかし、スマホ用にデザインを作り直すにあたり、cssがばらけていると困るので、
designfile内のcssに加えて、そのファイルからcssデータを読み込む形にしてください。
自分はとりあえず一ファイルだけやったのですが、ほかの記事の構成がよくわからなかったので、
全ての記事のcssを移す作業をしてほしいです。

**Comment by Nagarei** [comment]
1.
commom/css/*.css
はそのままで良い？
2.

``` css
#button_center{
    width: 340px;
    margin-left: auto;
    margin-right: auto;
}
```

(/production/2016/index.htmlより)
のような短いのも別のファイルに移さないとだめ？
